### ISSUE TITLE
LROAuth2 should send a Content-Type

### ISSUE THREAD

**Issue by jedisct1** [lukeredpath/LROAuth2Client#1]
Apparently, LROAuth2 doesn't send any Content-Type header especially when requesting an access token.

This causes some OAuth2 providers to fail as they don't parse the content of the POST request if there's no header like Content-Type: application/x-www-form-urlencoded .

**Comment by lukeredpath** [comment]
Explicitly set the content-type header of the token/refresh POST requests to application/x-www-form-encoded as some providers expect this. Closed by dcaf48098b892d1904d657a3ee2070b91e7fc231.

**Comment by lukeredpath** [comment]
Thanks for the report; I've made the change as suggested, let me know if this works for you now.
