### ISSUE TITLE
"expires_in" value is being ignored for refresh responses

### ISSUE THREAD

**Issue by precipice** [lukeredpath/LROAuth2Client#3]
At https://github.com/lukeredpath/LROAuth2Client/blob/master/Classes/LROAuth2AccessToken.m#L51, you are using the expires_in value from the initial access token, instead of updating the expires_in with a new expiration from the refresh response.  I read http://tools.ietf.org/html/draft-ietf-oauth-v2-11#section-5.2 to say that expires_in is a valid parameter in a refresh response, so I think ignoring that value is wrong. Otherwise, the access token is treated as valid for the initial expiration period, and then refreshed on every request after that.

I think the line should instead be:

```
NSTimeInterval expiresIn = (NSTimeInterval)[[_data valueForKey:@"expires_in"] intValue];
```

**Comment by lukeredpath** [comment]
When refreshing the token, the expires at value should be updated from the new token. (Closed by 78d359d43bd9852b9f33691502e7d3646f47b696)
